### ISSUE TITLE
InvalidTemplateResourceException

### ISSUE THREAD

**Issue by Patta** [frankbuijze/defbu_authenticator#2]
TYPO3 10.4.12
PHP 7.4
Composer mode
helhum/typo3-config-handling
helhum/typo3-secure-web

Exception on backend login:

`(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Standard->module" in format ".html", but none of the paths contained the expected template file (). The following paths were checked: REMOVED/private/typo3/sysext/backend/Resources/Private/Templates/`

**Comment by Patta** [comment]
The path to the LoginProvider.html in class LoginProvider is wrong.

is:
`GeneralUtility::getFileAbsFileName('EXT:defbu_authenticator/Resources/Private/Templates/LoginProvider.html')`

should:
`GeneralUtility::getFileAbsFileName('EXT:authenticator/Resources/Private/Templates/LoginProvider.html')`

I don't think this extension is currently compatible with TYPO3 10.4 LTS. 
All paths to extension files are wrong. Maybe a composer installation issue?

Would be great if you can provide a new release.
Many thanks.

**Comment by frankbuijze** [comment]
Since typo3 10.4 some additional places and templates are required. Basic 2FA on backend login still works, but relogin after session timeout and access to install and environment doe not work. The additional field is missing to make 2FA possible.

The app is called defbu_authenticator, but that is if one installs it without composer. Additional updates are required to make it 100% composer ready.

I will update the app as soon as time allows. Expect an update in March
